---
- name: Backup /etc/sudoers file to source ansible machine.
  hosts: all
  become: yes

  tasks:
  - name: Backup /etc/sudoers using fetch module
    fetch:
      src: /etc/sudoers
      dest: /home/ansible/sudoers_bkp/{{ inventory_hostname }}/
      flat: yes

