---
- hosts: all
  become: true
  tasks:
    - name: Create admin group
      group:
        name: admin
        state: present
    
    - name: Create developers group
      group:
        name: dev
        state: present
    
    - name: Create Orcale DBA group
      group:
        name: dba
        state: present