---
- name: Disable ipv6
  hosts: all
  become: yes

  tasks:
  - name: Disable IPV6 using blockinfile modfule
    blockinfile:
       path: /etc/sysctl.conf
       backup: yes
       block: |
           net.ipv6.conf.lo.disable_ipv6 = 1
           net.ipv6.conf.default.disable_ipv6 = 1
           net.ipv6.conf.all.disable_ipv6 = 1
  - name: Apply the change
    command: sysctl -a

