---
#bond0
- name: Compare pre & post bond0
  shell: diff_bond0=$(diff {{post.stdout}}/bond0_pre {{post.stdout}}/bond0_post);
         if [ -z $diff_bond0 ]; then echo "bond0_match";else echo "bond0_not_match";fi
  register: bond0_res
  when: ansible_bond0 is defined

- debug: 
    msg: "Bond0 status looks good on {{ ansible_hostname }}"
  when: ansible_bond0 is defined and bond0_res.stdout == "bond0_match"

- debug:
    msg: "NEED TO CHECK 'BOND0' ON {{ ansible_hostname }}"
  when: ansible_bond0 is defined and bond0_res.stdout == "bond0_not_match"

#bond1 

- name: Comparing pre & post bond1
  shell: diff_bond1=$(diff {{post.stdout}}/bond1_pre {{post.stdout}}/bond1_post);
         if [ -z $diff_bond1 ]; then echo "bond1_match";else echo "bond1_not_match";fi
  register: bond1_res
  when: ansible_bond1 is defined

- debug:
    msg: "Bond1 status looks good on {{ ansible_hostname }}"
  when: ansible_bond1 is defined and bond1_res.stdout == "bond1_match"

- debug:
    msg: "NEED TO CHECK 'BOND1' ON {{ ansible_hostname }}"
  when: ansible_bond1 is defined and bond1_res.stdout == "bond1_not_match"

#bond2
- name: Comparing pre & post bond2
  shell: diff_bond2=$(diff {{post.stdout}}/bond2_pre {{post.stdout}}/bond2_post);
         if [ -z $diff_bond2 ]; then echo "bond2_match";else echo "bond2_not_match";fi
  register: bond2_res
  when: ansible_bond2 is defined


- debug:
    msg: "Bond2 status looks good on {{ ansible_hostname }}"
  when: ansible_bond2 is defined and bond2_res.stdout == "bond2_match"

- debug:
    msg: "NEED TO CHECK 'BOND2' ON {{ ansible_hostname }}"
  when: ansible_bond2 is defined and bond2_res.stdout == "bond2_not_match"

#Adapter_info files comparison. 

- name: Comparing Pre & Post adapater_info
  shell: diff_adainf=$( diff {{post.stdout}}/adapter_info_pre {{post.stdout}}/adapter_info_post);
         if [ -z $diff_adainf ]; then echo "adainf_match"; else echo "adainf_not_match";fi
  register: adainf_stat

- debug: 
    msg: "Adapter_info status looks good on {{ ansible_hostname }}"
  when: adainf_stat.stdout == "adainf_match"

- debug:
    msg: "ADAPTER_INFO CHECKS MISMATCH ON {{ ansible_hostname }}"
  when: adainf_stat.stdout == "adainf_not_match"
