---
- name: Backup the status of bond0
  shell: cat /proc/net/bonding/bond0 > {{pre_folder}}/bond0_pre
  when: ansible_bond0 is defined

- name: Backup the status of bond1
  shell: cat /proc/net/bonding/bond1 > {{pre_folder}}/bond1_pre
  when: ansible_bond1 is defined

- name: Backup the status of bond2
  shell: cat /proc/net/bonding/bond2  > {{pre_folder}}/bond2_pre
  when: ansible_bond2 is defined

- name: Collecting ILO IP (OEL6)
  shell: /sbin/hponcfg -w {{pre_folder}}/ilo.txt &>/dev/null
  when:
    - ansible_distribution_major_version == '6'

- name: Collecting ILO IP (OEL7)
  shell: /usr/sbin/hponcfg -w {{pre_folder}}/ilo.txt &>/dev/null
  when:
    - ansible_distribution_major_version == '7'

- name: Collecting HBA status
  shell: /usr/bin/adapter_info > {{pre_folder}}/adapter_info_pre

- name: Checking powerpath status (OEL6)
  stat:
    path: /sbin/powermt
  register: powerpath
  when: ansible_distribution_major_version == '6'
  
- name: Collecting Powerpath details (OEL6)
  shell: /sbin/powermt display dev=all 2>/dev/null 1> {{pre_folder}}/powermt_pre
  when: 
    - ansible_distribution_major_version == '6'
    - powerpath.stat.exists

- name: Checking powerpath status (OEL7)
  stat:
    path: /usr/sbin/powermt
  register: powerpath_OEL7
  when: ansible_distribution_major_version == '7'

- name: Collecting Powerpath details (OEL7)
  shell: /sbin/powermt display dev=all 2>/dev/null 1> {{pre_folder}}/powermt_pre
  when: 
    - ansible_distribution_major_version == '7'
    - powerpath_OEL7.stat.exists


